/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransformIndexRouteImport } from './routes/transform/index'
import { Route as RemoveIndexRouteImport } from './routes/remove/index'
import { Route as ReduceIndexRouteImport } from './routes/reduce/index'
import { Route as CropIndexRouteImport } from './routes/crop/index'
import { Route as ConvertIndexRouteImport } from './routes/convert/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformIndexRoute = TransformIndexRouteImport.update({
  id: '/transform/',
  path: '/transform/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoveIndexRoute = RemoveIndexRouteImport.update({
  id: '/remove/',
  path: '/remove/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReduceIndexRoute = ReduceIndexRouteImport.update({
  id: '/reduce/',
  path: '/reduce/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropIndexRoute = CropIndexRouteImport.update({
  id: '/crop/',
  path: '/crop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertIndexRoute = ConvertIndexRouteImport.update({
  id: '/convert/',
  path: '/convert/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convert': typeof ConvertIndexRoute
  '/crop': typeof CropIndexRoute
  '/reduce': typeof ReduceIndexRoute
  '/remove': typeof RemoveIndexRoute
  '/transform': typeof TransformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convert': typeof ConvertIndexRoute
  '/crop': typeof CropIndexRoute
  '/reduce': typeof ReduceIndexRoute
  '/remove': typeof RemoveIndexRoute
  '/transform': typeof TransformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convert/': typeof ConvertIndexRoute
  '/crop/': typeof CropIndexRoute
  '/reduce/': typeof ReduceIndexRoute
  '/remove/': typeof RemoveIndexRoute
  '/transform/': typeof TransformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/convert' | '/crop' | '/reduce' | '/remove' | '/transform'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/convert' | '/crop' | '/reduce' | '/remove' | '/transform'
  id:
    | '__root__'
    | '/'
    | '/convert/'
    | '/crop/'
    | '/reduce/'
    | '/remove/'
    | '/transform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertIndexRoute: typeof ConvertIndexRoute
  CropIndexRoute: typeof CropIndexRoute
  ReduceIndexRoute: typeof ReduceIndexRoute
  RemoveIndexRoute: typeof RemoveIndexRoute
  TransformIndexRoute: typeof TransformIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transform/': {
      id: '/transform/'
      path: '/transform'
      fullPath: '/transform'
      preLoaderRoute: typeof TransformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remove/': {
      id: '/remove/'
      path: '/remove'
      fullPath: '/remove'
      preLoaderRoute: typeof RemoveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reduce/': {
      id: '/reduce/'
      path: '/reduce'
      fullPath: '/reduce'
      preLoaderRoute: typeof ReduceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop/': {
      id: '/crop/'
      path: '/crop'
      fullPath: '/crop'
      preLoaderRoute: typeof CropIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert/': {
      id: '/convert/'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertIndexRoute: ConvertIndexRoute,
  CropIndexRoute: CropIndexRoute,
  ReduceIndexRoute: ReduceIndexRoute,
  RemoveIndexRoute: RemoveIndexRoute,
  TransformIndexRoute: TransformIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
