/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CropImageIndexRouteImport } from './routes/crop-image/index'
import { Route as ConvertImageIndexRouteImport } from './routes/convert-image/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropImageIndexRoute = CropImageIndexRouteImport.update({
  id: '/crop-image/',
  path: '/crop-image/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertImageIndexRoute = ConvertImageIndexRouteImport.update({
  id: '/convert-image/',
  path: '/convert-image/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convert-image': typeof ConvertImageIndexRoute
  '/crop-image': typeof CropImageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convert-image': typeof ConvertImageIndexRoute
  '/crop-image': typeof CropImageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convert-image/': typeof ConvertImageIndexRoute
  '/crop-image/': typeof CropImageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/convert-image' | '/crop-image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/convert-image' | '/crop-image'
  id: '__root__' | '/' | '/convert-image/' | '/crop-image/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertImageIndexRoute: typeof ConvertImageIndexRoute
  CropImageIndexRoute: typeof CropImageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-image/': {
      id: '/crop-image/'
      path: '/crop-image'
      fullPath: '/crop-image'
      preLoaderRoute: typeof CropImageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert-image/': {
      id: '/convert-image/'
      path: '/convert-image'
      fullPath: '/convert-image'
      preLoaderRoute: typeof ConvertImageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertImageIndexRoute: ConvertImageIndexRoute,
  CropImageIndexRoute: CropImageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
